service: glad-starter

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

resources:
  Resources:
    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  signup:
    handler: src/authentication.signup
    events:
      - http:
          path: signup
          method: post
  login:
    handler: src/authentication.login
    events:
      - http:
          path: login
          method: post
  logout:
    handler: src/authentication.logout
    events:
      - http:
          path: logout
          method: post
